### ISSUE TITLE
[Bug]: Fresh install of UnityHub 3.9.1 will not start

### ISSUE THREAD

**Issue by comods** [flathub/com.unity.UnityHub#125]
### What Happened

Fresh install of UnityHub 3.9.1 will not start.

If I run UnityHub once with an invalid flag, it then will start.

I used:
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=start-unityhub --file-forwarding com.unity.UnityHub --help`

### How to Reproduce

```
flatpak uninstall com.unity.UnityHub
flatpak install com.unity.UnityHub
flatpak run com.unity.UnityHub        # crashes
flatpak run com.unity.UnityHub        # still crashes
flatpak run com.unity.UnityHub --help # works
flatpak run com.unity.UnityHub        # now works
```

### Operating System

Bazzite 40 (Fedora Atomic 40)

### Command-line output

```shell
Gtk-Message: 09:59:52.145: Failed to load module "colorreload-gtk-module"
Gtk-Message: 09:59:52.145: Failed to load module "window-decorations-gtk-module"
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '_concatLogs')
    at error (/app/extra/resources/app.asar/build/main/logger.js:121:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2:0922/095952.859315:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[2:0922/095952.859425:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
```

**Comment by RefinedSoftwareLLC** [comment]
```shell
Gtk-Message: 10:00:06.098: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:00:06.098: Failed to load module "window-decorations-gtk-module"
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '_concatLogs')
    at error (/app/extra/resources/app.asar/build/main/logger.js:121:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by RefinedSoftwareLLC** [comment]
```shell
Gtk-Message: 10:05:01.879: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:05:01.879: Failed to load module "window-decorations-gtk-module"
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[2:0922/100504.454720:ERROR:browser_main_loop.cc(271)] GLib: g_atomic_ref_count_dec: assertion 'old_value > 0' failed
```

**Comment by RefinedSoftwareLLC** [comment]
```shell
Gtk-Message: 10:16:48.305: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:16:48.305: Failed to load module "window-decorations-gtk-module"
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '_concatLogs')
    at error (/app/extra/resources/app.asar/build/main/logger.js:121:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2:0922/101650.671060:ERROR:browser_main_loop.cc(271)] GLib: g_atomic_ref_count_dec: assertion 'old_value > 0' failed
LaunchProcess: failed to execvp:
xdg-settings
[50:0922/101651.280347:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: DisplayRead|Scanout, format: YUV_420_BIPLANAR, share_between_threads: 0, gmb_type: platform
[50:0922/101651.280614:ERROR:shared_image_stub.cc(147)] SharedImageStub: Unable to create shared image
[50:0922/101654.989203:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```

**Comment by RefinedSoftwareLLC** [comment]
```shell
Gtk-Message: 10:05:33.912: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:05:33.912: Failed to load module "window-decorations-gtk-module"
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '_concatLogs')
    at error (/app/extra/resources/app.asar/build/main/logger.js:121:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2:0922/100536.310745:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
```

**Comment by RefinedSoftwareLLC** [comment]
Here is the output the first time it worked correctly:

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=start-unityhub --file-forwarding com.unity.UnityHub --help`

```shell
Gtk-Message: 10:06:42.555: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:06:42.555: Failed to load module "window-decorations-gtk-module"
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '_concatLogs')
    at error (/app/extra/resources/app.asar/build/main/logger.js:121:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
LaunchProcess: failed to execvp:
xdg-settings
[50:0922/100643.633425:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: DisplayRead|Scanout, format: YUV_420_BIPLANAR, share_between_threads: 0, gmb_type: platform
[50:0922/100643.633694:ERROR:shared_image_stub.cc(147)] SharedImageStub: Unable to create shared image
[50:0922/100647.406208:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[50:0922/100650.837332:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[50:0922/100650.845739:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by wjt** [comment]
I can't reproduce this.

I think this is most likely related to the runtime update. Try reverting 3875d540db5f34aec026e3fcc1abc5417c8d55a2 and see if you can still reproduce this.

Are you interested in maintaining this module?

**Comment by kilesduli** [comment]
Same issue, and I am using a laptop with hybrid A+N graphics.

**Comment by kilesduli** [comment]
> I can't reproduce this.
> 
> I think this is most likely related to the runtime update. Try reverting [3875d54](https://github.com/flathub/com.unity.UnityHub/commit/3875d540db5f34aec026e3fcc1abc5417c8d55a2) and see if you can still reproduce this.
> 
> Are you interested in maintaining this module?

I reverted to commit 3875d54. UnityHub opens normally, but there are still some errors, such as:
```
TypeError: Cannot read properties of undefined (reading '_concatLogs')
    at error (/app/extra/resources/app.asar/build/main/logger.js:121:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2:1012/093617.536085:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[2:1012/093617.536112:ERROR:browser_main_loop.cc(271)] GLib: g_atomic_ref_count_dec: assertion 'old_value > 0' failed
[2:1012/093617.536109:ERROR:browser_main_loop.cc(271)] GLib: g_variant_get_child_value: assertion 'index_ < g_variant_n_children (value)' failed
[2:1012/093617.536124:ERROR:browser_main_loop.cc(271)] GLib: g_atomic_ref_count_dec: assertion 'old_value > 0' failed
LaunchProcess: failed to execvp:
xdg-settings
```

It seems that the problem is not here.

**Comment by wjt** [comment]
Please try the test build on #128. Does that fix your problem?

**Comment by kilesduli** [comment]
> Please try the test build on #128. Does that fix your problem?

Yes, I tested it, and everything works fine. However, the type error still exists. It seems the problem is not related to this.

**Comment by JotaRata** [comment]
Same here. Fresh install UnityHub through KDE Discover and I get:
`TypeError: Cannot read properties of undefined (reading '_concatLogs')
    at error (/app/extra/resources/app.asar/build/main/logger.js:121:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by NoTuxNoBux** [comment]
Do I understand correctly that the original issue of not being able to start is solved with the latest version?

I doubt the JavaScript error is due to the Flatpak, unless it doesn't reproduce outside Flatpak.

**Comment by NoTuxNoBux** [comment]
Closing this issue due to inactivity and that it's likely resolved 😉.

@JulianGro Might be a momentary error due to something in the application itself if the updates included nothing related.
