### ISSUE TITLE
Crash on Edit > Preferences

### ISSUE THREAD

**Issue by katian** [flathub/com.unity.UnityHub#72]
Hello,

Ubuntu 22.04.1
Flatpak 1.12.7

When i select Edit > Preferences my 'basic' project crash.

[Editor.log](https://github.com/flathub/com.unity.UnityHub/files/9382537/Editor.log)

**Comment by rowbawts** [comment]
Same for me with the current LTS and latest stable versions of the editor. I tried built in pipeline and URP. Only version that works is 2020.3.40f1

5800X & 6700XT
Fedora 36 Silverblue
Flatpak 1.12.7

**Comment by rowbawts** [comment]
So what makes this really weird is I used it before on this system with nothing changed, so I checked what version of the editor was used for that project and installed that and the same issue occurs. So somehow the same version of the editor worked before and no longer does so I don't even think its an upstream editor issue. It must be something in the Flatpak environment likely the runtime causing the issue.

**Comment by KShivum** [comment]
Same thing here, I seem to crash on opening preferences and save layout on Fedora 36

**Comment by geekley** [comment]
I have same crash on basic empty project (without any package dependencies) in 2021.3.15f1.
It crashes when closing preferences window, or when opening build settings window.
It happens only from flatpak'd Unity Hub, not when directly executing Unity (without hub).
In case it helps investigating, crash shows this:
```
Obtained 26 stack frames.
#0  0x007fb79f36ee60 in funlockfile
#1  0x007fb79f3d02fd in g_type_check_instance
#2  0x007fb79f3c5e7c in g_signal_handlers_disconnect_matched
#3  0x00563cfefcc373 in DisconnectGtkSignal(void*, GtkCallbackResponse (*)(), void*)
#4  0x00563cfe86bf3d in MenuItem::~MenuItem()
#5  0x00563cfe8707b3 in RemoveItemFromMenu(std::list<MenuItem, std::allocator<MenuItem> >*, core::basic_string_ref<char>)
#6  0x00563cfe8707f3 in RemoveItemFromMenu(std::list<MenuItem, std::allocator<MenuItem> >*, core::basic_string_ref<char>)
#7  0x00563cfe870633 in MenuController::RemoveMenuItem(core::basic_string_ref<char>)
#8  0x00563cfd50c43c in Menu_CUSTOM_RemoveMenuItem(ScriptingBackendNativeStringPtrOpaque*)
#9  0x00000041023a73 in (wrapper managed-to-native) UnityEditor.Menu:RemoveMenuItem (string)
#10 0x00000041022bdf in UnityEditor.EditorApplication/<>c__DisplayClass104_0:<CallDelayed>b__0 ()
#11 0x007fb62e446228 in mono_get_runtime_build_info
#12 0x007fb62e5e4f8e in mono_runtime_invoke
#13 0x007fb62e5e4ed8 in mono_runtime_invoke
#14 0x00563cfddfd8e3 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
#15 0x00563cfdddb9f7 in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
#16 0x00563cfdf08c7f in Scripting::UnityEditor::EditorApplicationProxy::Internal_InvokeTickEvents(ScriptingExceptionPtr*)
#17 0x00563cfef2d41d in Application::TickTimer()
#18 0x00563cfefcb69e in MainMessageIteration(void*)
#19 0x007fb79af2218c in g_main_context_dispatch
#20 0x007fb79af22538 in g_main_context_dispatch
#21 0x007fb79af22853 in g_main_loop_run
#22 0x007fb797a77e85 in gtk_main
#23 0x00563cfefca85c in main
#24 0x007fb797643b80 in __libc_start_main
#25 0x00563cfd1b0029 in _start
```
I though it's be better to report here, since Unity devs would probably just say flatpak is not supported.

**Comment by rowbawts** [comment]
Ok so I recently reinstalled the latest (non pre-release) version and it seems to be working now, I haven't changed anything with my hardware so some update of some component seems to have resolved it.
